# -*- coding: utf-8 -*-
"""Coin flip simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PhhJlj5a5PgV3THVATSqZuAXAvFzQqN-
"""

import random
print("Hello. This a coin flip simulator. This will keep track of how many heads and tails are flipped. How many coin flips would you like me to record? ")
num_flips_string=input()
num_flips=0
while True:
  try:
    num_flips=int(num_flips_string)
    break
  except ValueError:
    print ("That is not a valid number. Please try again.")
    num_flips_string = input()
headcount=0
tailscount=0
for x in range(0,num_flips):
  random_int=random.randint(1,2)
  if random_int==1:
    headcount+=1
  else:
    tailscount+=1
print("Heads: ", headcount , " ", headcount/num_flips , "% of the total flips.")
print("Tails: ", tailscount , " ", tailscount/num_flips , "% of the total flips.")