# -*- coding: utf-8 -*-
"""Pi Simulator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJFR65OvMTIN9l_NMwm74pQqmb2P1-ZE
"""

print("Hello. This bot will generate pi to however many digits you would like (up to 100). How many digits would you like?")
x_string = (input())
pi = "141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117067"
newnumb = 0
while True:
  try:
    x = int(x_string)
    if x > 100:
      print("That is too many digits. Please try again.")
      x_string = input()
    else:
      break
  except ValueError:
    print("That is not a valid number. Please try again.")
    x_string = input()
newnumb = pi[0:x-1]
print ("3." + newnumb)