# -*- coding: utf-8 -*-
"""Sieve of Eratosthenes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMVkSnIZeDLCerVL32NJe5N8HB5Mn-7K
"""



import math

print ("Hello. The Sieve of Eratosthenes is an ancient method of finding all the prime numbers up to an integer. Pick an integer up to 10,000,000, and I will return all the primes that come before it.")
num_string = input()
num=0
while True:
  try:
    num=int(num_string)
    if num > 1000000:
      print ("Please enter an integer less than 1,000,000.")
      num_string = input()
    elif num < 0:
        print("Please enter a non-negative integer.")
    else:
      break
  except ValueError:
    print ("Please enter an integer.")
    num_string = input()
isPrime = [False, False] + [True]*(num-1)
for i in range(2, int(math.sqrt(num))+1):
  for x in range(0,len(isPrime)):
    if x%i==0 and x!=i:
      isPrime[x]=False
printList=list()
for index, value in enumerate(isPrime):
  if value==True:
    printList.append(index)
print(printList)